//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITINDEXAU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string OfficeNumber { get; set; }
        public string MobileNumber { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public string RegisteredIP { get; set; }
        public Nullable<System.DateTime> RegisteredDate { get; set; }
        public string VerificationCode { get; set; }
        public Nullable<System.DateTime> VerificationDate { get; set; }
        public Nullable<bool> Activated { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string LastLoginIP { get; set; }
        public Nullable<System.DateTime> LastChange { get; set; }
        public Nullable<bool> ResetPassword { get; set; }
        public Nullable<bool> AdminUser { get; set; }
        public Nullable<bool> Enabled { get; set; }
    }
}
